version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: fastfastapi
    binary: fastfastapi
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
  - id: ffa
    binary: ffa
    main: ./cmd/ffa
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w

archives:
  - id: fastfastapi
    builds:
      - fastfastapi
      - ffa
    name_template: "fastfastapi_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: markryangarcia
    name: fastfastapi
  draft: false
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
